<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
    <PackageReference Include="Unity" Version="5.11.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\DomainLayer.csproj" />
    <ProjectReference Include="..\Infraestructure\InfraestructureLayer.csproj" />
    <ProjectReference Include="..\Services\ApplicationLayer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\tbanc\source\repos\GestionHotelWinForms\src\Presentation2\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\account_circle.png" />
    <None Remove="Assets\bed.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\account_circle.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\bed.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\tbanc\source\repos\GestionHotelWinForms\src\Presentation2\.editorconfig" />
  </ItemGroup>

</Project>